#!/usr/bin/env ruby

require 'benchmark'
require 'optparse'
require 'colorize'

require 'simple_crawler'

def humanize_time(secs)
  [[60, :seconds], [60, :minutes], [24, :hours], [1000, :days]].map{ |count, name|
    if secs > 0
      secs, n = secs.divmod(count)
      "#{n.to_i} #{name}"
    end
  }.compact.reverse.join(' ')
end

options = {}

opt_parse = OptionParser.new do |opts|
    opts.banner = 'simple_crawler [options] url'

    opts.on('-f', '--file filename', 'Output result to file') do |file|
        options[:file] = file
    end

    opts.on_tail('-h', '--help', 'Show this message') do
        puts opts
        exit
    end

    # Another typical switch to print the version.
    opts.on_tail('-v', '--version', 'Show version') do
        puts SimpleCrawler::VERSION.colorize(:cyan)
        exit
    end
end

opt_parse.parse!

unless ARGV[0]
    puts opt_parse
    exit
end

elapsed = Benchmark.realtime do
    result = SimpleCrawler.crawl(ARGV[0])

    if options[:file]
        File.open(options.file, 'w') { |file| file.write(result) }
        exit
    end

    puts result.colorize(:green)
end

puts "Time spent crawling domain #{ARGV[0]} #{humanize_time elapsed}"
